[WIP]Delete周りの挙動
ventus-inc/proto_blow pull request #26
Opened 2017-08-10 00:55 UTC by tsukukobaan

## 対応するチケット

* https://trello.com/XX trelloのカード番号

## WHY
*

## WHAT

* 投稿APIのPOSTを実装
* すでに登録済みの場合にエラーを返す処理を実装

## HOW

## 確認すること

* [ ] 正しい挙動になっていること
    * [ ] 正しく登録できること
    * [ ] すでに登録済みの場合登録できないこと
* [ ] コードに問題がないこと
* [ ] 必要なテストが追加されていること
* [ ] テストがすべてパスしていること

2017-08-10 23:43 UTC, tsukukobaan commented on src/accounts/forms.py
> +    def clean_password2(self):
password2とする方が正しかった。
関連するattributeを引っ張ってくるため

2017-08-10 23:43 UTC, tsukukobaan commented on src/templates/base.html
> +            $(".deleteBtn").attr("href", "/tweet/"+parentId+"/delete/")
この直打ちっぽいのでいいのかは今後も検討

2017-08-10 23:44 UTC, tsukukobaan commented on src/templates/base.html
> +                xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
csrf_tokenエラー回避

2017-08-11 00:08 UTC, tsukukobaan commented on src/tweets/api/permissions.py
> +        return obj.from_user == request.user
書いたものの・・・・結局使ってないので残すか微妙

2017-08-11 00:11 UTC, tsukukobaan commented on src/tweets/api/views.py
> +        if obj_user != request_user:
IsOwnerを作ったが動かなかったので、結局ここでUser判定している。（自分のじゃない投稿を消せたらダメなので）
微妙だなぁ

2017-08-11 03:46 UTC, imtan submitted a review, later dismissed

2017-08-11 04:02 UTC, imtan requested changes
すんません！
レジスターする時、「password must match」って出るのでその修正をお願いします。

他に、こちら側で考えられる可能性があればコメントお願いします！

2017-08-11 04:02 UTC, imtan commented on src/accounts/forms.py
> +    def clean_password2(self):
すんません、registerでパスワードが一致してるのにユーザーが作れないかも
「password must mach」ってエラーが出ちゃいます！

2017-08-11 04:34 UTC, tsukukobaan commented on src/accounts/forms.py
> +    def clean_password2(self):
そう。だからここはpassword2の必要ありです。その修正をここでしました

2017-08-11 04:43 UTC, tsukukobaan commented
passwordマッチがしないという不具合を修正した行なので、手元で操作間違いないか確認して欲しいです

2017-08-11 05:36 UTC, imtan approved these changes

2017-08-11 12:10 UTC, merged